apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.application.service.type }}
  selector:
    app: {{ .Values.application.name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
